export enum Region {
  SEOUL = 'seoul',
  GYEONGGI = 'gyeonggi',
  INCHEON = 'incheon',
  BUSAN = 'busan',
  DAEGU = 'daegu',
  DAEJEON = 'daejeon',
  GWANGJU = 'gwangju',
  ULSAN = 'ulsan',
  GANGWON = 'gangwon',
  CHUNGCHEONG = 'chungcheong',
  JEOLLA = 'jeolla',
  GYEONGSANG = 'gyeongsang',
  JEJU = 'jeju',
  ETC = 'etc',
}
